#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Application.Resource", IsApplication=true)]

namespace Android_Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int mainImage = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mainImage3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int mainImage4 = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050041
			public const int a02 = 2131034177;
			
			// aapt resource value: 0x7f050046
			public const int a1012 = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int a1214 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int a1416 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int a1618 = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int a1820 = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int a2022 = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int a2224 = 2131034188;
			
			// aapt resource value: 0x7f050042
			public const int a24 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int a46 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int a68 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int a810 = 2131034181;
			
			// aapt resource value: 0x7f05000e
			public const int appointmentDetailsCityAddressOfAppointment = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int appointmentDetailsContactNumber = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int appointmentDetailsDate = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int appointmentDetailsFirstLineOfAddressOfAppointment = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int appointmentDetailsName = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int appointmentDetailsPostalCodeOfAppointment = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int appointmentDetailsSecondLineOfAddressOfAppointment = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int appointmentDetailsTime = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int cancelAppointment = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int confirmAppointment = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int dateOfAppointment = 2131034115;
			
			// aapt resource value: 0x7f05001c
			public const int helperDetailsBookAppointment = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int helperDetailsCity = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int helperDetailsContactNumber = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int helperDetailsCountry = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int helperDetailsFirstLine = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int helperDetailsName = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int helperDetailsPostcode = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int helperDetailsSecondLine = 2131034134;
			
			// aapt resource value: 0x7f05001b
			public const int helperDetailsSeeReviews = 2131034139;
			
			// aapt resource value: 0x7f050022
			public const int jnksdks = 2131034146;
			
			// aapt resource value: 0x7f05002f
			public const int linearLayout1 = 2131034159;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout2 = 2131034119;
			
			// aapt resource value: 0x7f05001d
			public const int loginEmailAddress = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int loginLoginAsElderly = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int loginLoginAsHelper = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int loginOrRegisterLogin = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int loginOrRegisterRegister = 2131034148;
			
			// aapt resource value: 0x7f05001f
			public const int loginPassword = 2131034143;
			
			// aapt resource value: 0x7f050001
			public const int nameOfHelper = 2131034113;
			
			// aapt resource value: 0x7f05002c
			public const int ratingBar = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int ratingNameOfHelper = 2131034155;
			
			// aapt resource value: 0x7f050038
			public const int registerCity = 2131034168;
			
			// aapt resource value: 0x7f050035
			public const int registerConfirmPassword = 2131034165;
			
			// aapt resource value: 0x7f050039
			public const int registerCountry = 2131034169;
			
			// aapt resource value: 0x7f050032
			public const int registerEmailAddress = 2131034162;
			
			// aapt resource value: 0x7f050036
			public const int registerFirstLine = 2131034166;
			
			// aapt resource value: 0x7f050030
			public const int registerFirstName = 2131034160;
			
			// aapt resource value: 0x7f050034
			public const int registerPassword = 2131034164;
			
			// aapt resource value: 0x7f05003a
			public const int registerPostalCode = 2131034170;
			
			// aapt resource value: 0x7f05003d
			public const int registerRegisterAsElderly = 2131034173;
			
			// aapt resource value: 0x7f05003c
			public const int registerRegisterAsHelper = 2131034172;
			
			// aapt resource value: 0x7f050037
			public const int registerSecondLine = 2131034167;
			
			// aapt resource value: 0x7f050031
			public const int registerSurname = 2131034161;
			
			// aapt resource value: 0x7f05003b
			public const int registerTelephoneNumber = 2131034171;
			
			// aapt resource value: 0x7f050033
			public const int registerUsername = 2131034163;
			
			// aapt resource value: 0x7f05003f
			public const int reviewComment = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int reviewNameOfHelper = 2131034174;
			
			// aapt resource value: 0x7f05002e
			public const int scrollView1 = 2131034158;
			
			// aapt resource value: 0x7f050012
			public const int setRating = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int setReview = 2131034131;
			
			// aapt resource value: 0x7f05004d
			public const int setTimetableSubmit = 2131034189;
			
			// aapt resource value: 0x7f05002d
			public const int submitRating = 2131034157;
			
			// aapt resource value: 0x7f050040
			public const int submitReview = 2131034176;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05001e
			public const int textView2 = 2131034142;
			
			// aapt resource value: 0x7f050002
			public const int textView3 = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int textView4 = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int textView5 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int timeOfAppointment = 2131034117;
			
			// aapt resource value: 0x7f050026
			public const int welcomeElderlyBookAnAppointment = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int welcomeElderlyListOfAppointments = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int welcomeElderlyName = 2131034149;
			
			// aapt resource value: 0x7f05002a
			public const int welcomeHelperListOfAppointments = 2131034154;
			
			// aapt resource value: 0x7f050028
			public const int welcomeHelperName = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int welcomeHelperSetTimetable = 2131034153;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int appointmentDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int appointmentDetailsScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bookAppointment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int helperDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loginOrRegister = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loginWelcomeElderly = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loginWelcomeHelpers = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ratingsScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int register = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int reviewScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int setTimetableTimes = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
